version: '2.2'
services:

  # nginx:
  #   depends_on:
  #     - sspmodule
  #   restart: always
  #   container_name: edssiregistrationportalnginx
  #   build: nginx
  #   volumes:
  #     - /home/centos/edssi_registration_portal/certs:/etc/nginx/certs/:ro
  #     - /home/centos/edssi_registration_portal/client_certs:/etc/nginx/client_certs/:ro
  #   ports:
  #     - "443:443"
  #   networks:
  #     - proxynet

  sspmodule:
    build: server
    container_name: sspmodule
    networks:
      - proxynet
    volumes:
      - /home/centos/ssp_module/server/.env:/app/.env
      - /home/centos/ssp_module/server/services/certificates:/app/services/certificates
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - 27017:27017
    networks:
      - my-proxy-net


networks:
  proxynet:
    name: custom_network
  my-proxy-net:
    external:
      name: custom_network